import type { NextPage } from 'next';
import Head from 'next/head';
import { BudgetInfo } from '../components/Budget';
import { Expenses } from '../components/Expenses';
import { AddButton } from '../components/Shared';

const Home: NextPage = () => {
  return (
    <section>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BudgetInfo />
      <Expenses />
      <AddButton />
    </section>
  );
};

export default Home;
